spring:
  config:
    import: optional:configserver:http://localhost:8888

  application:
    name: orderservice


#server:
#  port: 2240
#
#spring:
#  application:
#    name: orderservice
#  datasource:
#    url: jdbc:mysql://localhost:3306/ustemp
#    username: root
#    password: pass@word1
#    driverClassName: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true