
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 2238

spring:
  application:
    name: menuservice
  datasource:
    url: jdbc:mysql://localhost:3306/ustemp
    username: root
    password: pass@word1
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect